const peopleActionTypes = {
	FETCH_RANDOM_PEOPLE: "FETCH_RANDOM_PEOPLE",
	MARK_PERSON_AS_SHOWN: "MARK_PERSON_AS_SHOWN",
	ADD_PERSON_TO_FAVORITE: "ADD_PERSON_TO_FAVORITE",
};

export default peopleActionTypes;
