const peopleActionTypes = {
	SHOW_NEXT_PEOPLE: "SHOW_NEXT_PEOPLE",
	FETCH_RANDOM_PEOPLE: "FETCH_RANDOM_PEOPLE",
	ADD_PERSON_TO_FAVORITE: "ADD_PERSON_TO_FAVORITE",
};

export default peopleActionTypes;
